CREATE TABLE TABLE_MEMBER(
	memberId VARCHAR2(300),
	memberPw VARCHAR2(300),
	memberName VARCHAR2(300),
	memberAge NUMBER(3),
	memberGender VARCHAR2(20),
	memberEmail VARCHAR2(200),
	memberZipcode VARCHAR2(20),
	memberAddress VARCHAR2(300),
	memberAddressDetail VARCHAR2(300),
	memberAddressEtc VARCHAR2(100),
	CONSTRAINT MEMBER_PK PRIMARY KEY(memberId)
);


--제약조건 삭제
ALTER TABLE TABLE_MEMBER DROP CONSTRAINT MEMBER_PK;

SELECT *FROM TABLE_MEMBER;
INSERT INTO HR.TABLE_MEMBER
(MEMBERID, MEMBERPW, MEMBERNAME, MEMBERAGE, MEMBERGENDER, MEMBEREMAIL, MEMBERZIPCODE, MEMBERADDRESS, MEMBERADDRESSDETAIL, MEMBERADDRESSETC)
VALUES('홍길동', '1234', '홍길동', 10, '남', '홍길동', '서울', '강남', '강남', '강남');

CREATE TABLE MY_MEMBER(
   memberName VARCHAR2(300),
   memberEmail VARCHAR2(300),
   memberPw VARCHAR2(300),
   memberPhoneNum NUMBER(20),
   memberCountry VARCHAR2(20),
   memberIntro VARCHAR2(2000),   
   CONSTRAINT MYMEMBER_PK PRIMARY KEY(memberEmail)
);

CREATE TABLE MEMBER_HOBBY(
   hobby1 VARCHAR2(100),
   hobby2 VARCHAR2(100),
   hobby3 VARCHAR2(100),
   hobby4 VARCHAR2(100),
   hobby5 VARCHAR2(100),
   hobby6 VARCHAR2(100),
   hobby7 VARCHAR2(100),
   hobby8 VARCHAR2(100),
   memberEmail VARCHAR2(300),
   CONSTRAINT MEMBER_FK FOREIGN KEY(memberEmail)
   REFERENCES MY_MEMBER(memberEmail)
   );

SELECT * FROM MY_MEMBER;

SELECT * FROM MEMBER_HOBBY;




